name: 'Deploy package'

on:
  push:
    branches:
      - master
    paths:
      - ./packages/auto-import

jobs:
  publish:
    uses: ./.github/workflows/common-deploy.yml
    with:
      package-name: "@efebia/fastify-auto-import"
    secrets: inherit