name: 'Deploy @efebia/fastify-auto-import'

on:
  push:
    branches:
      - master
    paths:
      - ./packages/auto-import
      - ./.github/workflows/common-deploy.yml

jobs:
  publish:
    uses: ./.github/workflows/common-deploy.yml
    with:
      package-name: "@efebia/fastify-auto-import"
    secrets: inherit