name: 'Deploy @efebia/fastify-reply'

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths: ['./packages/fastify-reply/**', './.github/workflows/common-deploy.yml', './.github/workflows/fastify-reply.yml']

jobs:
  publish:
    uses: ./.github/workflows/common-deploy.yml
    with:
      package-name: "@efebia/fastify-reply"
    secrets: inherit