name: 'Deploy package'

on:
  push:
    branches:
      - master
    paths:
      - ./packages/hardhat-compile-monorepo

jobs:
  publish:
    uses: ./.github/workflows/common-deploy.yml
    with:
      package-name: "@efebia/hardhat-compile-monorepo"
    secrets: inherit