name: 'Deploy @efebia/hardhat-compile-monorepo'

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - ./packages/hardhat-compile-monorepo/**
      - ./.github/workflows/common-deploy.yml

jobs:
  publish:
    uses: ./.github/workflows/common-deploy.yml
    with:
      package-name: "@efebia/hardhat-compile-monorepo"
    secrets: inherit