name: 'Deploy package'

on:
  push:
    branches:
      - master
    paths:
      - ./packages/pino-mongodb
      - ./.github/workflows/common-deploy.yml

jobs:
  publish:
    uses: ./.github/workflows/common-deploy.yml
    with:
      package-name: "@efebia/pino-mongodb"
    secrets: inherit