name: 'Deploy @efebia/sqs-queue-v2'

on:
  push:
    branches:
      - master
    paths:
      - ./packages/sqs-queue-v2
      - ./.github/workflows/common-deploy.yml

jobs:
  publish:
    uses: ./.github/workflows/common-deploy.yml
    with:
      package-name: "@efebia/sqs-queue-v2"
    secrets: inherit