name: 'Deploy @efebia/sqs-queue-v2'

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths: ['packages/sqs-queue-v2/**', '.github/workflows/common-deploy.yml', '.github/workflows/sqs-queue-v2.yml']

jobs:
  publish:
    uses: ./.github/workflows/common-deploy.yml
    with:
      package-name: "@efebia/sqs-queue-v2"
      install-script: |
        yarn workspaces focus @efebia/sqs-queue-v2
        yarn workspace @efebia/queue build
    secrets: inherit