name: 'Deploy @efebia/sqs-queue-v3'

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - ./packages/sqs-queue-v3/**
      - ./.github/workflows/common-deploy.yml

jobs:
  publish:
    uses: ./.github/workflows/common-deploy.yml
    with:
      package-name: "@efebia/sqs-queue-v3"
    secrets: inherit